# -*- coding: utf-8 -*-
{
    'name': 'Donation App',
    'version': '14.0.0.0',
    'category': 'Accounting',
    'summary': 'Easy to donate money',
    'description': """
        Sample Module
    """,
    'author': 'Shubham',
    "price": 000,
    "currency": 'EUR',
    'website': 'https://www.agileinfoways.com',
    'depends': ['base','calendar'],
    'data': [
        'security/donation_security.xml',
        'security/ir.model.access.csv',
        'data/volunteer_role_data.xml',
        'data/ir_sequence_data.xml',
        'data/donation_scheduler.xml',
        'data/donation_email_template.xml',
        'report/report_view.xml',
        'views/donation_view.xml',
        'report/donation_report_view.xml',
        'views/expense_management.xml',
        'views/calendar_booking_views.xml',
        'views/calendar_event_views.xml',
        'views/calendar_template_booking.xml',
        'views/payment_management.xml',
        'views/registration_view.xml',
        'views/priest_management_view.xml',
        'views/volunteer_management_view.xml',
    ],
    'qweb': ['static/src/xml/base_calendar.xml'],
    'demo': [],
    'test': [],
    'installable': True,
    'auto_install': False,
    'live_test_url': '',
}
